version: '3.1'
services:
  app:
    container_name: microservice-eureka-service
    image: microservice-eureka-service
    build: ./
    ports:
      - "8761:8761"
#    depends_on:
 #     - postgresqldb
#  postgresqldb:
 #   image: postgres
 #   ports:
  #    - "5432:5432"
   # environment:
    #  - POSTGRES_PASSWORD=postgres
     # - POSTGRES_USER=postgres
      #- POSTGRES_DB=themeparkdb